cask '1password'
cask 'arc'
cask 'appcleaner'
cask 'docker'
brew 'eza'
brew 'fzf'
brew 'gh'
brew 'git-lfs'
brew 'golang'
brew 'httpie'
cask 'google-cloud-sdk'
cask 'ledger-live'
brew 'pipx'
cask 'superhuman'
brew 'terraform'
cask 'zed'
brew 'zoxide'

mas 'Bear – Markdown Notes', id: 1091189122
mas 'The Unarchiver', id: 425424353
