cask '1password'
cask 'arc'
cask 'appcleaner'
cask 'bambu-studio'
cask 'chatgpt'
cask 'cursor'
cask 'discord'
brew 'dockutil'
cask 'font-cascadia-code-nf'
cask 'google-chrome'
cask 'docker'
brew 'eza'
brew 'fzf'
brew 'gh'
cask 'ghostty'
brew 'git-lfs'
cask 'google-cloud-sdk'
brew 'httpie'
cask 'ledger-live'
cask 'notion'
cask 'notion-calendar'
cask 'raspberry-pi-imager'
cask 'superhuman'
brew 'terraform'
brew 'uv'
brew 'zoxide'

mas 'Flighty – Live Flight Tracker', id: 1358823008
mas 'Telegram', id: 747648890
mas 'WhatsApp Messenger', id: 310633997