eval "$(hub alias -s)"

export GOPATH=/Users/$(whoami)/go
export PATH=$PATH:/Users/$(whoami)/Library/Android/sdk/platform-tools:/Users/$(whoami)/.dotfiles/bin:$GOPATH/bin
export PATH=$PATH:/usr/local//Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin
