# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
zstyle :compinstall filename '/Users/eliottteissonniere/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# System zshrc for various things.
source /etc/zshrc

# Open new tabs in same directory
if [[ "$TERM_PROGRAM" == "Apple_Terminal" ]]; then
  function chpwd {
    printf '\e]7;%s\a' "file://$HOSTNAME${PWD// /%20}"
  }
  chpwd
fi

# Correct key mappings
bindkey -e
bindkey '[C' forward-word
bindkey '[D' backward-word

# Prompt
export PS1="%10F%m%f:%11F%1~%f \$ "

# Various environment variables
export CLICOLOR=1
export EDITOR=/usr/local/bin/subl
export GOPATH=/Users/$(whoami)/.go

# PATH specifics
export PATH=$PATH:/Users/$(whoami)/Library/Android/sdk/platform-tools
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin

# Aliases
eval "$(hub alias -s)"
alias ls=exa
